airboltic:
  outputs:

    dev:
      type: glue
      role_arn: arn:aws:iam::597088038232:role/GlueInteractiveSessionRole
      region: eu-north-1
      workers: 5
      worker_type: G.1X
      schema: airboltic
      database: airboltic
      session_provisioning_timeout_in_seconds: 120
      location: s3://air-boltic
      glue_session_reuse: True

  target: dev
